### ISSUE TITLE
The service is not running continuously and stops. 

### ISSUE THREAD

**Issue by yltsa** [kirbo/ruuvigw-mqtt-to-ha-auto-discovery#2]
Hi, the service is not running continuously and stops. Here ere are error messages from the log:

/ruuvigw2ha/index.js:116
      humidity: Number(humidity.toFixed(options.decimals.humidity || 2)),
                                ^
TypeError: Cannot read properties of undefined (reading 'toFixed')
    at handleData (/ruuvigw2ha/index.js:116:33)
    at MqttClient.<anonymous> (/ruuvigw2ha/index.js:39:5)
    at MqttClient.emit (node:events:527:28)
    at MqttClient._handlePublish (/ruuvigw2ha/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/ruuvigw2ha/node_modules/mqtt/lib/client.js:410:12)
    at work (/ruuvigw2ha/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/ruuvigw2ha/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/ruuvigw2ha/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/ruuvigw2ha/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/ruuvigw2ha/node_modules/readable-stream/lib/_stream_writable.js:307:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Kirbo** [comment]
That looks like you have something funky in the configurations. There might be a bug in my code as well, that's not outruled by any means, but I should be able to reproduce this, therefore I'd like to see the configuration you have (without the credentials obviously) 🙂

**Comment by Kirbo** [comment]
Here is the example configuration that you should have:
```yaml
mqtt_protocol: mqtt
mqtt_host: core-mosquitto
mqtt_port: 1883
mqtt_credentials:
  client_id: ruuvi-gw-mqtt-to-ha
  username: 
  password: 
mqtt_ha_topic: homeassistant/
mqtt_ruuvi_topic: ruuvi/#
mqtt_parsed_ruuvi_topic: ruuvi/parsed/
update_interval: 60
decimals:
  humidity: 2
  temperature: 2
  pressure: 2
  battery: 0
  voltage: 2
battery:
  minimum: 2000
  maximum: 3000
  low_battery: 2100
use_prefixes: true
```
